### ISSUE TITLE
Store shifts as well as indices

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/NeighbourLists.jl#14]
Please could you store the shift vectors `S` as well as the pair indices `i` and `j`? This would make it easier to recompute `r` and `R`, e.g. to implement a static neighbourlist. We could even consider no longer storing `r` and `R`.

**Comment by cortner** [comment]
thank you - one important discussion to have about this is whether it is worth making this change for Jv0.6.4 or whether it is enough to implement it for Jv1.x

**Comment by jameskermode** [comment]
I'm happy to switch to 1.x, especially if we get it working in Docker

**Comment by cortner** [comment]
the latest version of the package now stores `(i, j, shift)` - but I haven't exposed an AI for the shifts yet. What would be suitable? 
```
shift(nlist, idx)
```
where `idx` is the index of the pair? 

Another possibility I was thinking of was the following. At the moment `neigs(nlist, i)` returns `j, R` which are vectors of indices and directions of neighbours. I could add a second method 
```
j, R, shifts = neigss(nlist, i)
```

**Comment by jameskermode** [comment]
Great, thanks! Second option looks better to me. Presumably R is a displacement vector, not a direction cosine?

**Comment by cortner** [comment]
Yes correct.

**Comment by cortner** [comment]
Done in 08c20e527badfda6d110d86990a316fe9598a8a3

**Comment by cortner** [comment]
(only rudimentary tests - re-open if there are problems)
